import assert from 'node:assert/strict';
import test from 'node:test';
import { compareNginxPolicy, compareNginxPolicy301Flip } from './compare-nginx-policy.js';

const wrap = (maps, status = '302') => `# Generated by scripts/generate-nginx.js — do not edit by hand.
# redirect status: ${status}
# entries: path=1 query=0 not_found=0 gone=0
# This file is included from http context via 00-release-loader.conf.

${maps}

server {
  listen 80;
  server_name www.andy-y.cn andy-y.cn;
  if ($legacy_target != "") { return ${status} https://www.andy-y.cn$legacy_target; }
  return 301 https://www.andy-y.cn$request_uri;
}
`;

const baseMaps = `map $uri $legacy_target {
  default "";
  ~^/archives/76$ "/posts/asterisk-telephony42/";
}

map "$uri:$arg_p" $legacy_query_target {
  default "";
  "/:76" "/posts/asterisk-telephony42/";
}`;

test('identical nginx policy is allowed', () => {
  const text = wrap(baseMaps);
  const result = compareNginxPolicy(text, text);
  assert.equal(result.ok, true);
  assert.equal(result.added.length, 0);
});

test('additive new-post maps are allowed', () => {
  const current = wrap(baseMaps);
  const candidate = wrap(`map $uri $legacy_target {
  default "";
  ~^/archives/76$ "/posts/asterisk-telephony42/";
  ~^/archives/87$ "/posts/astro/";
  ~^/archives/87/$ "/posts/astro/";
}

map "$uri:$arg_p" $legacy_query_target {
  default "";
  "/:76" "/posts/asterisk-telephony42/";
  "/:87" "/posts/astro/";
}`);
  const result = compareNginxPolicy(current, candidate);
  assert.equal(result.ok, true);
  assert.equal(result.added.length, 3);
});

test('retargeted or removed maps are refused', () => {
  const current = wrap(baseMaps);
  const retargeted = wrap(`map $uri $legacy_target {
  default "";
  ~^/archives/76$ "/posts/other/";
}

map "$uri:$arg_p" $legacy_query_target {
  default "";
  "/:76" "/posts/asterisk-telephony42/";
}`);
  assert.equal(compareNginxPolicy(current, retargeted).ok, false);
  const removed = wrap(`map $uri $legacy_target {
  default "";
}

map "$uri:$arg_p" $legacy_query_target {
  default "";
  "/:76" "/posts/asterisk-telephony42/";
}`);
  assert.match(compareNginxPolicy(current, removed).reason, /removed/);
});

test('redirect status or server skeleton changes are refused', () => {
  const current = wrap(baseMaps, '302');
  assert.equal(compareNginxPolicy(current, wrap(baseMaps, '301')).ok, false);
  const movedRoot = current.replace('listen 80;', 'listen 8080;');
  assert.equal(compareNginxPolicy(current, movedRoot).ok, false);
});

test('301 flip comparator allows only legacy return-status change', () => {
  const current = wrap(baseMaps, '302');
  const flipped = wrap(baseMaps, '301');
  const result = compareNginxPolicy301Flip(current, flipped);
  assert.equal(result.ok, true);
  assert.equal(result.added.length, 0);
});

test('301 flip comparator refuses additive, retargeted, reverse, or skeleton drift', () => {
  const current = wrap(baseMaps, '302');
  const added = wrap(`map $uri $legacy_target {
  default "";
  ~^/archives/76$ "/posts/asterisk-telephony42/";
  ~^/archives/87$ "/posts/astro/";
}

map "$uri:$arg_p" $legacy_query_target {
  default "";
  "/:76" "/posts/asterisk-telephony42/";
}`, '301');
  assert.match(compareNginxPolicy301Flip(current, added).reason, /added/);
  const retargeted = wrap(`map $uri $legacy_target {
  default "";
  ~^/archives/76$ "/posts/other/";
}

map "$uri:$arg_p" $legacy_query_target {
  default "";
  "/:76" "/posts/asterisk-telephony42/";
}`, '301');
  assert.match(compareNginxPolicy301Flip(current, retargeted).reason, /retargeted/);
  assert.match(compareNginxPolicy301Flip(wrap(baseMaps, '301'), wrap(baseMaps, '302')).reason, /expected 302 -> 301/);
  const moved = wrap(baseMaps, '301').replace('listen 80;', 'listen 8080;');
  assert.equal(compareNginxPolicy301Flip(current, moved).ok, false);
});
